title: Shadowrun UK
description: A Shadowrun 5e game set in the UK
defaults:
    -
        scope:
            path: "AdventureLog"
        values:
            layout: adventureLog
    -
        scope:
            path: "Contacts"
        values:
            layout: contacts
    -
        scope:
            path: "Miscellaneous"
        values:
            layout: miscellaneous
